# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EISAir' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EISAir
  pod "AFNetworking"
  pod 'CocoaLumberjack'
  pod 'JSONModel'
  pod 'SDWebImage'
  #pod 'BlocksKit'
  pod 'MBProgressHUD'
  pod 'TPKeyboardAvoiding'
  #pod 'WebViewJavascriptBridge'
  #pod 'NJKWebViewProgress'
  pod 'SZTextView'
  pod 'Masonry'
  #pod 'Realm'

  target 'EISAirTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
